name: medical_learning_ai
description: "A new Flutter project."
publish_to: 'none' 

version: 1.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1 
  firebase_storage: ^12.1.3
  firebase_remote_config: ^5.0.4 
  firebase_ml_model_downloader: ^0.3.0+4
  firebase_vertexai: ^0.2.2+4

  # Additional packages
  fl_chart: ^0.68.0
  intl: ^0.19.0
  shared_preferences: ^2.0.15 
  flutter_markdown: ^0.6.10  # この行を追加

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "/Users/vv01sam/workplace/katekyo/katekyo_flutter_app/assets/images/fukuro_icon.png"
  adaptive_icon_background: "#FFFFFF" # Android用の背景色を指定
  adaptive_icon_foreground: "/Users/vv01sam/workplace/katekyo/katekyo_flutter_app/assets/images/fukuro_icon.png" # Android用の前景アイコン

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/medical_learning_ai.png