// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS9b_G0aYasDaOtJnZglbpO9_ASaMPoDY',
    appId: '1:185764290891:web:0f2ba31af78e6af880c8ce',
    messagingSenderId: '185764290891',
    projectId: 'medical-learning-ai-e8032',
    authDomain: 'medical-learning-ai-e8032.firebaseapp.com',
    storageBucket: 'medical-learning-ai-e8032.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFOk3TMeyaDFOiXeoTcIsTB92o-Ijdh04',
    appId: '1:185764290891:android:cd1fbdcf3ce565a780c8ce',
    messagingSenderId: '185764290891',
    projectId: 'medical-learning-ai-e8032',
    storageBucket: 'medical-learning-ai-e8032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAGge6vUFwwj6ZkKoBLULtPNUNM_CoTVc',
    appId: '1:185764290891:ios:1a78792db9773f1980c8ce',
    messagingSenderId: '185764290891',
    projectId: 'medical-learning-ai-e8032',
    storageBucket: 'medical-learning-ai-e8032.appspot.com',
    iosBundleId: 'com.example.medicalLearningAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAGge6vUFwwj6ZkKoBLULtPNUNM_CoTVc',
    appId: '1:185764290891:ios:1a78792db9773f1980c8ce',
    messagingSenderId: '185764290891',
    projectId: 'medical-learning-ai-e8032',
    storageBucket: 'medical-learning-ai-e8032.appspot.com',
    iosBundleId: 'com.example.medicalLearningAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS9b_G0aYasDaOtJnZglbpO9_ASaMPoDY',
    appId: '1:185764290891:web:c22000a5387efa7b80c8ce',
    messagingSenderId: '185764290891',
    projectId: 'medical-learning-ai-e8032',
    authDomain: 'medical-learning-ai-e8032.firebaseapp.com',
    storageBucket: 'medical-learning-ai-e8032.appspot.com',
  );
}
